---
title: "Module 4: Estimation and Model Fitting"
author: 
  - name: "Adam Spiegler"
    affiliation: "University of Colorado Denver"
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 2
    toc-expand: 1
    embed-resources: true
editor: source
execute:
  eval: false
title-block-banner: true
#warning: false
license: "CC BY-NC-SA"
---

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Additional Reading

---

- [Chapter 3 Linear Model Estimation](https://jfrench.github.io/LinearRegression/linear-model-estimation.html) from *A Progressive Introduction to Linear Models*
- Chapter 1 of *Applied Linear Regression* ([link to library ebook](https://go.exlibris.link/69jsQwWW))




# What is a Regression Model? 

---

::: {.callout-note title="Definition" appearance="simple"}
[**Regression models**]{style="color:blue} are used to model the relationship between:

- One or more [**response**]{style="color:blue"} (also called outcome, output, or dependent) and 
- One or more [**predictor**]{style="color:blue"}  (also called feature, explanatory, regressor, input, or dependent) variables.
- Predictor variables $X_i$ are used to predict the value of the response variable $Y$ with error $\epsilon$.

$$  Y = f(X_1, X_2, \ldots X_p) + \epsilon $$ 

Because the variables in our model are often interrelated, describing these variables as independent or dependent variables is vague and is best avoided.
:::

A distinction is sometimes made between regression models and classification models. In that case:


- [Regression models]{style="color:blue"} attempt to predict a numerical response.
- [Classification models]{style="color:blue"} attempt to predict the level that a categorical response will have.



The basic goals of a regression model are most commonly:


1. [Describe relationships]{style="color:red"} (associations) between predictor variables and the response. 

> What is the general relationship between the selling price of a home and the number of bedrooms the home has?
  
2. [Predict future or unknown response values]{style="color:red"} based on specified values of the predictors. 

> If I add a bedroom, how much will my the selling price of my home go up?



With our regression model, we also hope to be able to:


1. [Generalize]{style="color:red"} our results from the sample to a larger population of interest. 

> After doing a double-blind, placebo trial on an experimental vaccine, is it safe for the general public?

2. [Infer causality]{style="color:red"} between our predictors and the response. 

> Did receiving the vaccine lead to a drop in infection rates? Hospitalizations?


Our regression model will not be able to perfectly fit a *true model*  to the data. Thus, **finding the true model should not be the goal** of a regression analysis. A regression analysis should attempt to **find a model that adequately describes the relationship** between the response and relevant predictor variables (either in terms of prediction, association, generalization, causality, etc.)



# Linear Models

---

::: {.callout-note title="Definition" appearance="simple"}
A [**linear model**]{style="color:blue"} is a regression model in which the regression coefficients enter the model linearly. For example:

$$Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \ldots + \beta_p X_p + \epsilon .$$ {#eq:lmdef}

The model does not need to be linear in predictor variables:

$$ Y = \beta_0 + \beta_1 X_1^2 + \beta_2 e^{X_2+X_3^2} +  \beta_3 \ln{(X_1X_2X_3)} + \epsilon $$

The $\beta_i$'s are called the [**regression coefficients**]{style="color:blue"}, and these are unknown parameters we will estimate.
:::

## Question 1

---

Determine whether each of the models below is a linear model.


a. $\displaystyle Y = \beta_0 + \beta_1 \left( X_1X_2X_3 \right) + \beta_2 e^{X_1^2+X_2^2+X_3^2} + \beta_3 \ln{(X_3)} + \epsilon$ 

b. $\displaystyle Y = \beta_0 \left(X_1^{\beta_1}+ X_2^{\beta_2} + X_3^{\beta_2} \right) + \epsilon$ 

c. $\displaystyle Y = \beta_0 \left(X_1^{\beta_1}X_2^{\beta_2} X_3^{\beta_2} \right) \epsilon$ 

### Solution to Question 1

---



<br>  
<br>  


### Bonus Question

---

For the model(s) that are not linear, can you transform the model into a linear model?


#### Solution to Bonus Question

---



<br>  
<br>  


::: {.callout-note appearance="simple"}
The [response variable]{style="color:blue"} $Y$: 

- Is treated as a random variable.
- We can observe values (denoted $\hat{Y}$) of $Y$ at each observation in our data set.
:::

::: {.callout-note appearance="simple"}
We denote $X_1$, $X_2$, \ldots, $X_p$ as the [predictor variables]{style="color:blue"}.

- The predictor variables are treated as non-random (fixed) values.
- Each observation can be expressed as $(X_1, X_2, \ldots , X_p)$.
:::



